const productos = [
    {
      id: 1,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQBtJLdLLsQMOnaBm9Om5mnMkZ3UQLk5vqYrA&usqp=CAU",
      title: "Producto 1",
      price: 19.99,
      description: "100% algodón, todas tallas sadasdasdad23123131132",
      category: "remeras",
      quantity: 1,
      colors: ['Rojo', 'Azul', 'Verde'],
      sizes: ['S', 'M', 'L', 'XL'],
      selectedColor: '',
      selectedSize: '', 
    },
    {
      id: 2,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQBtJLdLLsQMOnaBm9Om5mnMkZ3UQLk5vqYrA&usqp=CAU",
      title: "Producto 2",
      price: 29.99,
      description: "100% algodón, todas  tallas sadasdadsad23123131132",
      category: "shorts",
      quantity: 1,
      colors: ['Rojo', 'Azul', 'Verde'],
      sizes: ['S', 'M', 'L', 'XL'],
      selectedColor: '',
      selectedSize: '', 
    },
    {
      id: 3,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQBtJLdLLsQMOnaBm9Om5mnMkZ3UQLk5vqYrA&usqp=CAU",
      title: "Producto 3",
      price: 39.99,
      description: "100% algodón, todas tallas sadasdasds231231311329874",
      category: "pantalones",
      quantity: 1,
      colors: ['Rojo', 'Azul', 'Verde'],
      sizes: ['S', 'M', 'L', 'XL'],
      selectedColor: '',
      selectedSize: '', 
    },
    {
      id: 4,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQBtJLdLLsQMOnaBm9Om5mnMkZ3UQLk5vqYrA&usqp=CAU",
      title: "Producto 4",
      price: 49.99,
      description: "Descripción del Producto 4",
      category: "shorts",
      quantity: 1,
      colors: ['Rojo', 'Azul', 'Verde'],
      sizes: ['S', 'M', 'L', 'XL'],
      selectedColor: '',
      selectedSize: '', 
    },
    {
      id: 5,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQBtJLdLLsQMOnaBm9Om5mnMkZ3UQLk5vqYrA&usqp=CAU",
      title: "Producto 5",
      price: 59.99,
      description: "Descripción del Producto 5",
      category: "otros",
      quantity: 1,
      colors: ['Rojo', 'Azul', 'Verde'],
      sizes: ['S', 'M', 'L', 'XL'],
      selectedColor: '',
      selectedSize: '', 
    },
    {
      id: 6,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQBtJLdLLsQMOnaBm9Om5mnMkZ3UQLk5vqYrA&usqp=CAU",
      title: "Producto 6",
      price: 69.99,
      description: "Descripción del Producto 6",
      category: "shorts",
      quantity: 1,
      colors: ['Rojo', 'Azul', 'Verde'],
      sizes: ['S', 'M', 'L', 'XL'],
      selectedColor: '',
      selectedSize: '', 
    },
    {
      id: 7,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQBtJLdLLsQMOnaBm9Om5mnMkZ3UQLk5vqYrA&usqp=CAU",
      title: "Producto 7",
      price: 79.99,
      description: "Descripción del Producto 7",
      category: "accesorios",
      quantity: 1,
      colors: ['Rojo', 'Azul', 'Verde'],
      sizes: ['S', 'M', 'L', 'XL'],
      selectedColor: '',
      selectedSize: '', 
    },
    {
      id: 8,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQBtJLdLLsQMOnaBm9Om5mnMkZ3UQLk5vqYrA&usqp=CAU",
      title: "Producto 8",
      price: 89.99,
      description: "Descripción del Producto 8",
      category: "conjuntos",
      quantity: 1,
      colors: ['Rojo', 'Azul', 'Verde'],
      sizes: ['S', 'M', 'L', 'XL'],
      selectedColor: '',
      selectedSize: '', 
    },
    {
      id: 9,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQBtJLdLLsQMOnaBm9Om5mnMkZ3UQLk5vqYrA&usqp=CAU",
      title: "Producto 9",
      price: 99.99,
      description: "Descripción del Producto 9",
      category: "shorts",
      quantity: 1,
      colors: ['Rojo', 'Azul', 'Verde'],
      sizes: ['S', 'M', 'L', 'XL'],
      selectedColor: '',
      selectedSize: '', 
    },
    {
      id: 10,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQBtJLdLLsQMOnaBm9Om5mnMkZ3UQLk5vqYrA&usqp=CAU",
      title: "Producto 10",
      price: 109.99,
      description: "Descripción del Producto 10",
      category: "accesorios",
      quantity: 1,
      colors: ['Rojo', 'Azul', 'Verde'],
      sizes: ['S', 'M', 'L', 'XL'],
      selectedColor: '',
      selectedSize: '', 
    }
];
